### ISSUE TITLE
Why do I get different results when I try to use transforms?

### ISSUE THREAD

**Issue by xxliu893** [naklecha/llama3-from-scratch#20]
```
import torch
import transformers
import json

model = transformers.AutoModelForCausalLM.from_pretrained('meta-llama/Meta-Llama-3-8B')
tokenizer = transformers.AutoTokenizer.from_pretrained('meta-llama/Meta-Llama-3-8B',model_max_length=512,padding_side="right",use_fast=False,)

dim = model.config.hidden_size
n_layers = model.config.num_hidden_layers
n_heads = model.config.num_attention_heads
n_kv_heads = model.config.num_key_value_heads
vocab_size = model.config.vocab_size
#The following two lines of code seem to be useless
multiple_of = model.config.multiple_of if model.config.multiple_of else 1024
ffn_dim_multiplier = model.config.ffn_dim_multiplier if model.config.ffn_dim_multiplier else 1.3

norm_eps = model.config.rms_norm_eps
rope_theta = model.config.rope_theta

prompt = "the answer to the ultimate question of life, the universe, and everything is "
tokens = tokenizer.encode(prompt)
print(tokens)
tokens = torch.tensor(tokens)
prompt_split_as_tokens = [tokenizer.decode([token.item()]) for token in tokens]
print(prompt_split_as_tokens)
embedding_layer = torch.nn.Embedding(vocab_size, dim)
tok_embeddings_weight = model.model.embed_tokens.weight
embedding_layer.weight.data.copy_(tok_embeddings_weight)
token_embeddings_unnormalized = embedding_layer(tokens).to(torch.bfloat16)
token_embeddings_unnormalized.shape

def rms_norm(tensor, norm_weights):
    return (tensor * torch.rsqrt(tensor.pow(2).mean(-1, keepdim=True) + norm_eps)) * norm_weights

#RoPE
zero_to_one_split_into_64_parts = torch.tensor(range(64))/64
zero_to_one_split_into_64_parts

freqs = 1.0 / (rope_theta ** zero_to_one_split_into_64_parts)
freqs

freqs_for_each_token = torch.outer(torch.arange(17), freqs)
freqs_cis = torch.polar(torch.ones_like(freqs_for_each_token), freqs_for_each_token)
freqs_cis.shape

final_embedding = token_embeddings_unnormalized
for layer in range(n_layers):
    qkv_attention_store = []
    layer_embedding_norm = rms_norm(final_embedding, model.model.layers[layer].post_attention_layernorm.weight)
    q_layer = model.model.layers[layer].self_attn.q_proj.weight
    q_layer = q_layer.view(n_heads, q_layer.shape[0] // n_heads, dim)
    k_layer = model.model.layers[layer].self_attn.k_proj.weight
    k_layer = k_layer.view(n_kv_heads, k_layer.shape[0] // n_kv_heads, dim)
    v_layer = model.model.layers[layer].self_attn.v_proj.weight
    v_layer = v_layer.view(n_kv_heads, v_layer.shape[0] // n_kv_heads, dim)
    w_layer = model.model.layers[layer].self_attn.o_proj.weight.to(torch.bfloat16)
    for head in range(n_heads):
        q_layer_head = q_layer[head]
        k_layer_head = k_layer[head//4]
        v_layer_head = v_layer[head//4]
        q_per_token = torch.matmul(layer_embedding_norm, q_layer_head.T)
        k_per_token = torch.matmul(layer_embedding_norm, k_layer_head.T)
        v_per_token = torch.matmul(layer_embedding_norm, v_layer_head.T).to(torch.bfloat16)
        q_per_token_split_into_pairs = q_per_token.float().view(q_per_token.shape[0], -1, 2)
        q_per_token_as_complex_numbers = torch.view_as_complex(q_per_token_split_into_pairs)
        q_per_token_split_into_pairs_rotated = torch.view_as_real(q_per_token_as_complex_numbers * freqs_cis)
        q_per_token_rotated = q_per_token_split_into_pairs_rotated.view(q_per_token.shape)
        k_per_token_split_into_pairs = k_per_token.float().view(k_per_token.shape[0], -1, 2)
        k_per_token_as_complex_numbers = torch.view_as_complex(k_per_token_split_into_pairs)
        k_per_token_split_into_pairs_rotated = torch.view_as_real(k_per_token_as_complex_numbers * freqs_cis)
        k_per_token_rotated = k_per_token_split_into_pairs_rotated.view(k_per_token.shape)
        qk_per_token = torch.matmul(q_per_token_rotated, k_per_token_rotated.T)/(128)**0.5
        mask = torch.full((len(token_embeddings_unnormalized), len(token_embeddings_unnormalized)), float("-inf"))
        mask = torch.triu(mask, diagonal=1)
        qk_per_token_after_masking = qk_per_token + mask
        qk_per_token_after_masking_after_softmax = torch.nn.functional.softmax(qk_per_token_after_masking, dim=1).to(torch.bfloat16)
        qkv_attention = torch.matmul(qk_per_token_after_masking_after_softmax, v_per_token)
        qkv_attention_store.append(qkv_attention)
    stacked_qkv_attention = torch.cat(qkv_attention_store, dim=-1)
    #w_layer = model[f"layers.{layer}.attention.wo.weight"]
    embedding_delta = torch.matmul(stacked_qkv_attention, w_layer.T)
    embedding_after_edit = final_embedding + embedding_delta
    embedding_after_edit_normalized = rms_norm(embedding_after_edit, model.model.layers[layer].input_layernorm.weight)
    w1 = model.model.layers[layer].mlp.gate_proj.weight
    w2 = model.model.layers[layer].mlp.down_proj.weight
    w3 = model.model.layers[layer].mlp.up_proj.weight
    output_after_feedforward = torch.matmul(torch.functional.F.silu(torch.matmul(embedding_after_edit_normalized, w1.T)) * torch.matmul(embedding_after_edit_normalized, w3.T), w2.T)
    final_embedding = embedding_after_edit+output_after_feedforward
	
final_embedding = rms_norm(final_embedding, model.model.norm.weight)
final_embedding.shape

logits = torch.matmul(final_embedding[-1], model.lm_head.weight.T)
logits.shape

next_token = torch.argmax(logits, dim=-1)
next_token
>>>tensor(8168)
tokenizer.decode([next_token.item()])
>>>';&'
my question：Why is the result not 42?
```

**Comment by zhanzushun** [comment]
after some fixes it works @xxliu893 

1. load model with param torch_dtype
2. swtich input_layernorm and post_attention_layernorm
3. permute and reshape q_layer and k_layer

```
import torch
import transformers
import json

model = transformers.AutoModelForCausalLM.from_pretrained('meta-llama/Meta-Llama-3-8B', torch_dtype=torch.bfloat16)
tokenizer = transformers.AutoTokenizer.from_pretrained('meta-llama/Meta-Llama-3-8B',model_max_length=512,padding_side="right",use_fast=False,)

dim = model.config.hidden_size
n_layers = model.config.num_hidden_layers
n_heads = model.config.num_attention_heads
n_kv_heads = model.config.num_key_value_heads
vocab_size = model.config.vocab_size
norm_eps = model.config.rms_norm_eps
rope_theta = model.config.rope_theta

prompt = "the answer to the ultimate question of life, the universe, and everything is "
tokens = tokenizer.encode(prompt)
print(tokens)
tokens = torch.tensor(tokens)
prompt_split_as_tokens = [tokenizer.decode([token.item()]) for token in tokens]
print(prompt_split_as_tokens)

embedding_layer = torch.nn.Embedding(vocab_size, dim)
embedding_layer.weight.data.copy_(model.model.embed_tokens.weight)
token_embeddings_unnormalized = embedding_layer(tokens).to(torch.bfloat16)

def rms_norm(tensor, norm_weights):
    return (tensor * torch.rsqrt(tensor.pow(2).mean(-1, keepdim=True) + norm_eps)) * norm_weights

#RoPE
zero_to_one_split_into_64_parts = torch.tensor(range(64))/64
freqs = 1.0 / (rope_theta ** zero_to_one_split_into_64_parts)
freqs_for_each_token = torch.outer(torch.arange(17), freqs)
freqs_cis = torch.polar(torch.ones_like(freqs_for_each_token), freqs_for_each_token)

mask = torch.full((len(token_embeddings_unnormalized), len(token_embeddings_unnormalized)), float("-inf"))
mask = torch.triu(mask, diagonal=1)

final_embedding = token_embeddings_unnormalized
for layer in range(n_layers):
    qkv_attention_store = []
    token_embeddings = rms_norm(final_embedding, model.model.layers[layer].input_layernorm.weight)

    q_layer = model.model.layers[layer].self_attn.q_proj.weight
    q_layer = q_layer.view(n_heads, 2, q_layer.shape[0]//n_heads//2, dim).permute(0,2,1,3).reshape(n_heads, q_layer.shape[0]//n_heads, dim)
    k_layer = model.model.layers[layer].self_attn.k_proj.weight
    k_layer = k_layer.view(n_kv_heads, 2, k_layer.shape[0]//n_kv_heads//2, dim).permute(0,2,1,3).reshape(n_kv_heads, k_layer.shape[0]//n_kv_heads, dim)
    v_layer = model.model.layers[layer].self_attn.v_proj.weight
    v_layer = v_layer.view(n_kv_heads, v_layer.shape[0]//n_kv_heads, dim)

    for head in range(n_heads):
        q_layer_head = q_layer[head]
        k_layer_head = k_layer[head//4]
        v_layer_head = v_layer[head//4]

        q_per_token = torch.matmul(token_embeddings, q_layer_head.T)
        q_per_token_split_into_pairs = q_per_token.float().view(q_per_token.shape[0], -1, 2)
        q_per_token_as_complex_numbers = torch.view_as_complex(q_per_token_split_into_pairs)
        q_per_token_as_complex_numbers_rotated = q_per_token_as_complex_numbers * freqs_cis
        q_per_token_split_into_pair_rotated = torch.view_as_real(q_per_token_as_complex_numbers_rotated)
        q_per_token_rotated = q_per_token_split_into_pair_rotated.view(q_per_token.shape)

        k_per_token = torch.matmul(token_embeddings, k_layer_head.T)
        k_per_token_split_into_pairs = k_per_token.float().view(k_per_token.shape[0], -1, 2)
        k_per_token_as_complex_numbers = torch.view_as_complex(k_per_token_split_into_pairs)
        k_per_token_as_complex_numbers_rotated = k_per_token_as_complex_numbers * freqs_cis
        k_per_token_split_into_pair_rotated = torch.view_as_real(k_per_token_as_complex_numbers_rotated)
        k_per_token_rotated = k_per_token_split_into_pair_rotated.view(k_per_token.shape)

        qk_per_token = torch.matmul(q_per_token_rotated, k_per_token_rotated.T)/(128)**0.5
        qk_per_token_after_masking = qk_per_token + mask
        qk_per_token_after_masking_after_softmax = torch.nn.functional.softmax(qk_per_token_after_masking, dim=1).to(torch.bfloat16)

        v_per_token = torch.matmul(token_embeddings, v_layer_head.T)
        qkv_attention = torch.matmul(qk_per_token_after_masking_after_softmax, v_per_token) # 17*128
        qkv_attention_store.append(qkv_attention)

    stacked_qkv_attention = torch.cat(qkv_attention_store, dim=-1)
    w_layer = model.model.layers[layer].self_attn.o_proj.weight
    embedding_delta = torch.matmul(stacked_qkv_attention, w_layer.T)
    embedding_after_edit = final_embedding + embedding_delta
    embedding_after_edit_normalized = rms_norm(embedding_after_edit, model.model.layers[layer].post_attention_layernorm.weight)
    w1 = model.model.layers[layer].mlp.gate_proj.weight
    w2 = model.model.layers[layer].mlp.down_proj.weight
    w3 = model.model.layers[layer].mlp.up_proj.weight
    output_after_feedforward = torch.matmul(torch.functional.F.silu(torch.matmul(embedding_after_edit_normalized, w1.T)) * torch.matmul(embedding_after_edit_normalized, w3.T), w2.T)
    final_embedding = embedding_after_edit+output_after_feedforward

final_embedding = rms_norm(final_embedding, model.model.norm.weight)
logits = torch.matmul(final_embedding[-1], model.lm_head.weight.T)
next_token = torch.argmax(logits, dim=-1)
print(next_token)
final_token = tokenizer.decode([next_token.item()])
print(final_token)
```

**Comment by xxliu893** [comment]
`q_layer.view(n_heads, 2, q_layer.shape[0]//n_heads//2, dim).permute(0,2,1,3).reshape(n_heads, q_layer.shape[0]//n_heads, dim)`
Can you explain why it is necessary to perform the permute operation and why the value 2 is chosen? @zhanzushun

**Comment by xxliu893** [comment]
> after some fixes it works @xxliu893
> 
>     1. load model with param torch_dtype
> 
>     2. swtich input_layernorm and post_attention_layernorm
> 
>     3. permute and reshape q_layer and k_layer
> 
> 
> ```
> import torch
> import transformers
> import json
> 
> model = transformers.AutoModelForCausalLM.from_pretrained('meta-llama/Meta-Llama-3-8B', torch_dtype=torch.bfloat16)
> tokenizer = transformers.AutoTokenizer.from_pretrained('meta-llama/Meta-Llama-3-8B',model_max_length=512,padding_side="right",use_fast=False,)
> 
> dim = model.config.hidden_size
> n_layers = model.config.num_hidden_layers
> n_heads = model.config.num_attention_heads
> n_kv_heads = model.config.num_key_value_heads
> vocab_size = model.config.vocab_size
> norm_eps = model.config.rms_norm_eps
> rope_theta = model.config.rope_theta
> 
> prompt = "the answer to the ultimate question of life, the universe, and everything is "
> tokens = tokenizer.encode(prompt)
> print(tokens)
> tokens = torch.tensor(tokens)
> prompt_split_as_tokens = [tokenizer.decode([token.item()]) for token in tokens]
> print(prompt_split_as_tokens)
> 
> embedding_layer = torch.nn.Embedding(vocab_size, dim)
> embedding_layer.weight.data.copy_(model.model.embed_tokens.weight)
> token_embeddings_unnormalized = embedding_layer(tokens).to(torch.bfloat16)
> 
> def rms_norm(tensor, norm_weights):
>     return (tensor * torch.rsqrt(tensor.pow(2).mean(-1, keepdim=True) + norm_eps)) * norm_weights
> 
> #RoPE
> zero_to_one_split_into_64_parts = torch.tensor(range(64))/64
> freqs = 1.0 / (rope_theta ** zero_to_one_split_into_64_parts)
> freqs_for_each_token = torch.outer(torch.arange(17), freqs)
> freqs_cis = torch.polar(torch.ones_like(freqs_for_each_token), freqs_for_each_token)
> 
> mask = torch.full((len(token_embeddings_unnormalized), len(token_embeddings_unnormalized)), float("-inf"))
> mask = torch.triu(mask, diagonal=1)
> 
> final_embedding = token_embeddings_unnormalized
> for layer in range(n_layers):
>     qkv_attention_store = []
>     token_embeddings = rms_norm(final_embedding, model.model.layers[layer].input_layernorm.weight)
> 
>     q_layer = model.model.layers[layer].self_attn.q_proj.weight
>     q_layer = q_layer.view(n_heads, 2, q_layer.shape[0]//n_heads//2, dim).permute(0,2,1,3).reshape(n_heads, q_layer.shape[0]//n_heads, dim)
>     k_layer = model.model.layers[layer].self_attn.k_proj.weight
>     k_layer = k_layer.view(n_kv_heads, 2, k_layer.shape[0]//n_kv_heads//2, dim).permute(0,2,1,3).reshape(n_kv_heads, k_layer.shape[0]//n_kv_heads, dim)
>     v_layer = model.model.layers[layer].self_attn.v_proj.weight
>     v_layer = v_layer.view(n_kv_heads, v_layer.shape[0]//n_kv_heads, dim)
> 
>     for head in range(n_heads):
>         q_layer_head = q_layer[head]
>         k_layer_head = k_layer[head//4]
>         v_layer_head = v_layer[head//4]
> 
>         q_per_token = torch.matmul(token_embeddings, q_layer_head.T)
>         q_per_token_split_into_pairs = q_per_token.float().view(q_per_token.shape[0], -1, 2)
>         q_per_token_as_complex_numbers = torch.view_as_complex(q_per_token_split_into_pairs)
>         q_per_token_as_complex_numbers_rotated = q_per_token_as_complex_numbers * freqs_cis
>         q_per_token_split_into_pair_rotated = torch.view_as_real(q_per_token_as_complex_numbers_rotated)
>         q_per_token_rotated = q_per_token_split_into_pair_rotated.view(q_per_token.shape)
> 
>         k_per_token = torch.matmul(token_embeddings, k_layer_head.T)
>         k_per_token_split_into_pairs = k_per_token.float().view(k_per_token.shape[0], -1, 2)
>         k_per_token_as_complex_numbers = torch.view_as_complex(k_per_token_split_into_pairs)
>         k_per_token_as_complex_numbers_rotated = k_per_token_as_complex_numbers * freqs_cis
>         k_per_token_split_into_pair_rotated = torch.view_as_real(k_per_token_as_complex_numbers_rotated)
>         k_per_token_rotated = k_per_token_split_into_pair_rotated.view(k_per_token.shape)
> 
>         qk_per_token = torch.matmul(q_per_token_rotated, k_per_token_rotated.T)/(128)**0.5
>         qk_per_token_after_masking = qk_per_token + mask
>         qk_per_token_after_masking_after_softmax = torch.nn.functional.softmax(qk_per_token_after_masking, dim=1).to(torch.bfloat16)
> 
>         v_per_token = torch.matmul(token_embeddings, v_layer_head.T)
>         qkv_attention = torch.matmul(qk_per_token_after_masking_after_softmax, v_per_token) # 17*128
>         qkv_attention_store.append(qkv_attention)
> 
>     stacked_qkv_attention = torch.cat(qkv_attention_store, dim=-1)
>     w_layer = model.model.layers[layer].self_attn.o_proj.weight
>     embedding_delta = torch.matmul(stacked_qkv_attention, w_layer.T)
>     embedding_after_edit = final_embedding + embedding_delta
>     embedding_after_edit_normalized = rms_norm(embedding_after_edit, model.model.layers[layer].post_attention_layernorm.weight)
>     w1 = model.model.layers[layer].mlp.gate_proj.weight
>     w2 = model.model.layers[layer].mlp.down_proj.weight
>     w3 = model.model.layers[layer].mlp.up_proj.weight
>     output_after_feedforward = torch.matmul(torch.functional.F.silu(torch.matmul(embedding_after_edit_normalized, w1.T)) * torch.matmul(embedding_after_edit_normalized, w3.T), w2.T)
>     final_embedding = embedding_after_edit+output_after_feedforward
> 
> final_embedding = rms_norm(final_embedding, model.model.norm.weight)
> logits = torch.matmul(final_embedding[-1], model.lm_head.weight.T)
> next_token = torch.argmax(logits, dim=-1)
> print(next_token)
> final_token = tokenizer.decode([next_token.item()])
> print(final_token)
> ```

Running ok！

**Comment by ericwudocomoi** [comment]
for the permute, check [https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py](url), line 153:
` def permute(w, n_heads, dim1=dim, dim2=dim):
        return w.view(n_heads, dim1 // n_heads // 2, 2, dim2).transpose(1, 2).reshape(dim1, dim2)`

So when the original LLama3 models are converted to HF compatible model, q and k mats are already permuted for convenience of rotary positional encoding

**Comment by xxliu893** [comment]
> for the permute, check [https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py](url), line 153: ` def permute(w, n_heads, dim1=dim, dim2=dim): return w.view(n_heads, dim1 // n_heads // 2, 2, dim2).transpose(1, 2).reshape(dim1, dim2)`
> 
> So when the original LLama3 models are converted to HF compatible model, q and k mats are already permuted for convenience of rotary positional encoding

I understand, thanks for your answer
