### ISSUE TITLE
why decoding final_embedding[-1] is the next token?

### ISSUE THREAD

**Issue by jrryzh** [naklecha/llama3-from-scratch#21]
Thanks for this great tutorial, really detailed and clear, taught me a lot!!

My question is, as the final_embedding originally come from the prompt, then why is decoding final_embedding[-1] gives the next token? Hope can get an answer, thanks!

**Comment by naklecha** [comment]
The final embedding for each token is the predicted embedding of the next token. During inference, we only need to predict the token after the sentence (which is why we only look for the prediction of the last token).
